WIP openid session fix #68
opendistro-for-elasticsearch/security-kibana-plugin pull request #72
Opened 2019-08-05 19:23 UTC by shamsalmon

Tracking the fix to https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/issues/68

I tracked the problem down to this: https://forum.search-guard.com/t/keycloak-authentication-and-searchguard-problems/1174/3

Which lead me to this: https://github.com/floragunncom/search-guard-kibana-plugin/commit/e9000569245eb60bb7c75b784a41772184a2de51#diff-fcb5ceb54f21f2db198925c7ecabe50c

However... even with the same code it still is throwing a 302 when i would be expecting it to throw a 401 ideally.

Here is the flow:
- Session attempts to go through authentication flow
https://github.com/shamsalmon/security-kibana-plugin/blob/a131da819969c28f03cf5c5cd05338e64ad24393/lib/auth/types/AuthType.js#L188

- Cookie goes through validation 
https://github.com/shamsalmon/security-kibana-plugin/blob/a131da819969c28f03cf5c5cd05338e64ad24393/lib/auth/types/AuthType.js#L204

- Validation marks cookie as expired
https://github.com/shamsalmon/security-kibana-plugin/blob/a131da819969c28f03cf5c5cd05338e64ad24393/lib/auth/types/AuthType.js#L294

- Authtype redirects to openid handler for unauth... which redirects to bell @ /auth/openid/login
https://github.com/shamsalmon/security-kibana-plugin/blob/a131da819969c28f03cf5c5cd05338e64ad24393/lib/auth/types/AuthType.js#L211 

It never actually enters our oauth2 auth handler because bell is sending the 302...

2019-08-07 04:53 UTC, shamsalmon commented
I tracked down what is happening here... if I delete the cookies so cookie validator is never ran then we get to the point where headers are considered (from an ajax request) and a 401 is sent. 

You will only notice this happening if your session timeouts are very low. Mine is set to 1 minute.

Every instance of a recent version of Keyclock I have stood up will not respond to CORS the way this expects even with web origins added, and this will be broken for you. 

This is fixable by moving the logic where its checking the header above where the cookie validation is sending it to onUnathenticated.

2019-08-07 05:19 UTC, shamsalmon commented
Remediate session issues by using the code above and setting `opendistro_security.cookie.ttl` to the same expration as the setting in your keycloak client.

What this will do is skip the cookievalidation errors I posted about above and instead validate your ajax request and send a 401 if it is one.

It will then handle the 401 on the frontend and redirect you through a login flow that does not require CORS.

What this does not fix:
POST requests after the session expires. If you wait for the session and cookie to expire you will see POST requests returning a 401 but not redirecting. This is because the UI error handler that handles the login flow for 401s does not account for POST requests. What it should do is reauth you but instead it just throws an auth error. That needs to be fixed.

2019-08-07 14:41 UTC, shamsalmon commented
@hardik-k-shah

2019-08-14 09:49 UTC, shamsalmon commented
This is now fixed for post requests with the latest commit. The flow looks like this if you are going through XHR:

Request sent -> Backend sends 401 if session is expired and cookie has not been invalidated (cookie expiration (ttl setting) must be higher than session expiration) -> Frontend captures 401 and does a window.location redirect forcing a reauthentication window.

This *should* also fix SAML and every other provider that relies on the same workflow.

2019-12-19 17:49 UTC, rofreytag commented
+1 Please include this in an upcoming patch. 

We love using kibana behind SAML, the session loss errors are really annoying.

2019-12-19 19:54 UTC, shamsalmon commented
My latest change fixes the json parsing issue on the frontend handler. I removed formatting stuff and things odfe 1.2 security plugin fixes.

2020-01-13 11:28 UTC, agarwalgovind commented
Hi Sam,

Are the latest changes involves using refresh_token for access_token renewal when we use odfe with OpenID and Keycloak or currently there is some other way to renew the access_token till SSO session is valid.

2020-01-14 16:24 UTC, shamsalmon commented
> Hi Sam,
> 
> Are the latest changes involves using refresh_token for access_token renewal when we use odfe with OpenID and Keycloak or currently there is some other way to renew the access_token till SSO session is valid.

This change only forces a redirect if the session is expired. Access / Refresh token changes will require some significant changes.

2020-03-26 19:07 UTC, chasebrewsky commented
+1 We currently have an OpenID authentication token that expires every 5 minutes for security purposes. Without this change we have to refresh the page constantly to keep the session alive.

2020-03-27 15:06 UTC, shamsalmon commented
> +1 We currently have an OpenID authentication token that expires every 5 minutes for security purposes. Without this change we have to refresh the page constantly to keep the session valid. We also have the same issue that agarwalgovind has, where we are issuing a refresh token but it never gets used to refresh the access token.

I am no longer currently using Open Distro for my work. I looked into the change required to make a request for a new token and it doesn't seem overly complicated. Here is a link to the auth api that Open Distro uses. https://github.com/hapijs/bell/blob/master/API.md. There is a section there about refresh tokens which you can use to generate a new token. I was planning on implementing this at some point but I haven't had the time unfortunately.

2020-03-27 15:32 UTC, chasebrewsky commented
> I am no longer currently using Open Distro for my work. I looked into the change required to make a request for a new token and it doesn't seem overly complicated. Here is a link to the auth api that Open Distro uses. https://github.com/hapijs/bell/blob/master/API.md. There is a section there about refresh tokens which you can use to generate a new token. I was planning on implementing this at some point but I haven't had the time unfortunately.

That's alright, after reviewing a lot of the pull requests that have been in the queue vs what is actually getting pulled in it looks like they've been prioritizing pull requests from internal employees over external requests for some time now.

I also looked at the code last night and noticed something similar. The biggest thing I noticed was that each full page load redirected to the OpenID authentication endpoint instead of tracking the expiration of the actual token given in the token response, attempting a refresh, and continuing on. I'm guessing this is because the functionality didn't exactly fit into the interface for the plugin or requires implementation specific middleware?

Did you end up using just plain old Elasticsearch in the end?

2020-03-31 19:26 UTC, shamsalmon commented
> > I am no longer currently using Open Distro for my work. I looked into the change required to make a request for a new token and it doesn't seem overly complicated. Here is a link to the auth api that Open Distro uses. https://github.com/hapijs/bell/blob/master/API.md. There is a section there about refresh tokens which you can use to generate a new token. I was planning on implementing this at some point but I haven't had the time unfortunately.
> 
> That's alright, after reviewing a lot of the pull requests that have been in the queue vs what is actually getting pulled in it looks like they've been prioritizing pull requests from internal employees over external requests for some time now.
> 
> I also looked at the code last night and noticed something similar. The biggest thing I noticed was that each full page load redirected to the OpenID authentication endpoint instead of tracking the expiration of the actual token given in the token response, attempting a refresh, and continuing on. I'm guessing this is because the functionality didn't exactly fit into the interface for the plugin or requires implementation specific middleware?
> 
> Did you end up using just plain old Elasticsearch in the end?

No although we have plans to implement Open Distro within the next few months. Its just not current at the top of my to-dos. 

The behavior you are seeing is because refresh tokens are not utilized at all as far as I can tell. The bell oauth library does not seem to automate that as much as I am sure they would hope.

2020-05-27 14:07 UTC, james-od commented
Another +1 to this
Our engineers are finding it frustrating to have to re-navigate to their indexes several times a day due to session timeouts, getting this fix in would be fantastic.
Thanks!

2020-05-28 19:14 UTC, fatalglitch commented
+1 Let's get this moving to fix this issue

2020-05-29 09:11 UTC, agarwalgovind commented
Hello,

I have a fix for the issue. Will be raising a PR. The fix is for ODFE - 0.9 w.r.t to Kibana 6.7.
After approval and thorough review the fix can be patched to higher version also.

2020-11-24 19:59 UTC, seraphjiang commented on public/chrome/configuration/enable_configuration.js
> +            var data = null;
use ```let``` than ```var```

2020-11-24 20:01 UTC, seraphjiang requested changes
would you rebase from master

2020-11-28 09:24 UTC, seraphjiang commented
Close PR as no response, feel free to reopen

2020-11-28 09:24 UTC, closed without merging

2020-11-30 14:57 UTC, rofreytag commented
Oh no, so sad about this getting closed.

I hope either the original author or another maintainer can re-open this. We have been waiting for a fix on this a while now.  
I can only repeat what @james-od said, it is a time-burner to constantly need to refresh or re-login to kibana due to this issue.

2020-11-30 15:12 UTC, agarwalgovind commented
Hello,

There is a PR for the above issue - [](https://github.com/opendistro-for-elasticsearch/security-kibana-plugin/pull/217.) It being tracked under a new ticket.